#! /usr/bin/env bash
# $1=model $2=version
MODEL="$1"
VER="$2"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}"   )" && pwd   )"
ROOT=$(dirname ${SCRIPT_DIR})
MV=${MODEL}_${VER}
ROOTFS=$ROOT/rootfs/$MV
RAMDISK=$ROOT/ramdisk/$MV
PAT=$ROOT/pat/$MV
WORKDIR=$ROOT/$MV
TOOLCHAIN=$ROOT/toolchain/$MV

sudo rm -rf $PAT $ROOTFS $RAMDISK $WORKDIR $TOOLCHAIN
